# Generated by Django 5.2 on 2025-05-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.IntegerField(max_length=20, verbose_name='Количество средств')),
                ('currency', models.CharField(choices=[('RUB', 'Российский Рубль'), ('USD', 'Американский Доллар'), ('CNY', 'Китайский Юань'), ('AMD', 'Армянский драм'), ('GEL', 'Грузинский лари')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('method', models.CharField(choices=[('SBP', 'СБП'), ('On_account', 'На банковский счет')], default='SBP', verbose_name='Способ перевода')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения операции')),
                ('bank_account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_from', to='accounts.bankaccount', verbose_name='Счет снятия средств')),
                ('bank_account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_to', to='accounts.bankaccount', verbose_name='Счет пополнения средств')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
            },
        ),
    ]
