# Generated by Django 5.2 on 2025-05-03 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='summ',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-20000), django.core.validators.MaxValueValidator(20000)], verbose_name='Количество средств'),
        ),
    ]
