# Generated by Django 5.2 on 2025-05-03 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_currency_remove_user_second_name_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='summ',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-20000), django.core.validators.MaxValueValidator(20000)], verbose_name='Количество средств'),
        ),
    ]
