# Generated by Django 5.2 on 2025-05-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
        ('transactions', '0002_alter_transaction_currency_alter_transaction_summ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='summ',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Количество средств'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_from', to='accounts.bankaccount', verbose_name='Счет снятия средств'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_to', to='accounts.bankaccount', verbose_name='Счет пополнения средств'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('SBP', 'СБП'), ('account', 'На банковский счет')], default='SBP', verbose_name='Способ перевода'),
        ),
    ]
