# Generated by Django 5.2 on 2025-05-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
        ('transactions', '0003_remove_transaction_summ_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_account_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_from', to='accounts.bankaccount', verbose_name='Счет снятия средств'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_to', to='accounts.bankaccount', verbose_name='Счет пополнения средств'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('SBP', 'Перевод по СБП'), ('Account', 'Перевод на банковский счет'), ('Withdraw', 'Снятие средств'), ('Deposit', 'Пополнение средств')], default='SBP', verbose_name='Тип транзакции'),
        ),
    ]
