# Generated by Django 5.2 on 2025-05-03 06:53

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, validators=[accounts.models.validate_username], verbose_name='Имя')),
                ('second_name', models.CharField(max_length=80, validators=[accounts.models.validate_username], verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[accounts.models.validate_phone], verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, validators=[accounts.models.validate_account], verbose_name='Номер счета')),
                ('type', models.CharField(choices=[('Debit', 'Дебетовый'), ('Credit', 'Кредитный'), ('Contribution', 'Вклад')], default='Debit', max_length=12, verbose_name='Тип счета')),
                ('currency', models.CharField(choices=[('RUB', 'Российский Рубль'), ('USD', 'Американский Доллар'), ('CNY', 'Китайский Юань'), ('AMD', 'Армянский драм'), ('GEL', 'Грузинский лари')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('balance', models.IntegerField(default=0, verbose_name='Количество средств')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания счета')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения счета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'bank_accounts',
            },
        ),
    ]
