# Generated by Django 5.2 on 2025-05-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_currency_remove_user_second_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='isMain',
            field=models.BooleanField(default=False, null=True, verbose_name='Основной счет'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency', verbose_name='Валюта'),
        ),
    ]
