# Generated by Django 5.2 on 2025-05-04 09:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_ismain_alter_bankaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество средств'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='course',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Курс относительно рубля'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='kod',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[accounts.models.validate_username], verbose_name='Username'),
        ),
    ]
