# Generated by Django 5.2 on 2025-05-04 09:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bankaccount_balance_alter_currency_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[accounts.models.validate_username], verbose_name='Username'),
        ),
    ]
