# Generated by Django 5.2 on 2025-05-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='kod',
            new_name='code',
        ),
    ]
